/* Generated By:JavaCC: Do not edit this line. ermConstants.java */
package mer;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface ermConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTITY_RELATIONSHIP_MODEL = 5;
  /** RegularExpression Id. */
  int ENTITY = 6;
  /** RegularExpression Id. */
  int RELATIONED = 7;
  /** RegularExpression Id. */
  int TO = 8;
  /** RegularExpression Id. */
  int ALPHABETIC = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"entity_relationship_model\"",
    "\"entity\"",
    "\"relationed\"",
    "\"to\"",
    "<ALPHABETIC>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
  };

}
