/* Generated By:JavaCC: Do not edit this line. rastreabilityMatrixConstants.java */
package rastreability;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface rastreabilityMatrixConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RELATIONSHIP = 5;
  /** RegularExpression Id. */
  int RASTREABILITY_MATRIX = 6;
  /** RegularExpression Id. */
  int CROSSCUTTING = 7;
  /** RegularExpression Id. */
  int ERMODEL = 8;
  /** RegularExpression Id. */
  int LINE = 9;
  /** RegularExpression Id. */
  int COLUMN = 10;
  /** RegularExpression Id. */
  int CELL = 11;
  /** RegularExpression Id. */
  int CONTRIBUTION = 12;
  /** RegularExpression Id. */
  int CORRELATION = 13;
  /** RegularExpression Id. */
  int GOAL_REF = 14;
  /** RegularExpression Id. */
  int TASK_REF = 15;
  /** RegularExpression Id. */
  int SOFTGOAL_REF = 16;
  /** RegularExpression Id. */
  int ALPHABETIC = 17;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 21;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 22;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 23;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"relationship\"",
    "\"rastreability_matrix\"",
    "\"crosscutting\"",
    "\"ERmodel\"",
    "\"line\"",
    "\"column\"",
    "\"cell\"",
    "\"contribution\"",
    "\"correlation\"",
    "\"goal_ref\"",
    "\"task_ref\"",
    "\"softgoal_ref\"",
    "<ALPHABETIC>",
    "\"//\"",
    "<token of kind 19>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 24>",
    "\"(\"",
    "\";\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"=\"",
  };

}
