/* Generated By:JavaCC: Do not edit this line. aovgraphTreeConstants.java Version 4.1d1 */
package aov;

public interface aovgraphTreeConstants
{
  public int JJTASPECT_ORIENTED_MODEL = 0;
  public int JJTGOAL_MODEL = 1;
  public int JJTCOMPONENT = 2;
  public int JJTSOFTGOAL = 3;
  public int JJTGOAL = 4;
  public int JJTTASK = 5;
  public int JJTNOMECOMPONENTE = 6;
  public int JJTTOPIC = 7;
  public int JJTRELATIONSHIP = 8;
  public int JJTCORRELATION = 9;
  public int JJTCROSSCUTTING_REL = 10;
  public int JJTPOINTCUT = 11;
  public int JJTPOINTCUT_EXPRESSION = 12;
  public int JJTOPERAND = 13;
  public int JJTREGULAR_EXPRESSION = 14;
  public int JJTADVICE = 15;
  public int JJTJOINPOINT = 16;
  public int JJTJOINPOINTCROSSCUTTING = 17;
  public int JJTA_IT_EXPRESSION = 18;
  public int JJTINTERTYPE_DECLARATION = 19;


  public String[] jjtNodeName = {
    "aspect_oriented_model",
    "goal_model",
    "component",
    "softgoal",
    "goal",
    "task",
    "nomeComponente",
    "topic",
    "relationship",
    "Correlation",
    "crosscutting_rel",
    "pointcut",
    "pointcut_expression",
    "operand",
    "regular_expression",
    "advice",
    "joinpoint",
    "joinpointcrosscutting",
    "a_it_expression",
    "intertype_declaration",
  };
}
/* JavaCC - OriginalChecksum=edadfe2e41f51af28ffafee7628f08b6 (do not edit this line) */
